{{
    config
    ({"materialized": 'table',
    "schema": 'TRANSFORM'})
    
}}

WITH country_details_transform AS

(

SELECT

SOURCE_DATA:name:official::VARCHAR AS COUNTRY_OFFICIAL_NAME,

SOURCE_DATA:name:common::VARCHAR AS COUNTRY_COMMON_NAME,

SOURCE_DATA:latlng::VARCHAR AS COUNTRY_LATLNG,

CON.VALUE::VARCHAR AS COUNTRY_CONTINENT_NAME,

SOURCE_DATA:region::VARCHAR AS COUNTRY_REGION_NAME,

SOURCE_DATA:subregion::VARCHAR AS COUNTRY_SUBREGION_NAME,

SOURCE_DATA:capital::VARCHAR AS COUNTRY_CAPITAL_NAME,

SOURCE_DATA:capitalInfo:latlng::VARCHAR AS COUNTRY_CAPITAL_LATLNG,

SOURCE_DATA:area::INT AS COUNTRY_TOTAL_AREA,

SOURCE_DATA:population::INT AS COUNTRY_POPULATION,

CUR.KEY::VARCHAR AS COUNTRY_CURRENCY,

CUR.VALUE:name::VARCHAR AS COUNTRY_CURRENCY_NAME,

CUR.VALUE:symbol::VARCHAR AS COUNTRY_CURRENCY_SYMBOL,

SOURCE_DATA:flags:png::VARCHAR AS COUNTRY_FLAG,

SOURCE_DATA:maps:googleMaps::VARCHAR AS COUNTRY_MAP,

SOURCE_DATA:languages::VARCHAR AS COUNTRY_LANGUAGE,

SOURCE_DATA:startOfWeek::VARCHAR AS COUNTRY_START_OF_WEEK,

SOURCE_DATA:unMember::BOOLEAN AS COUNTRY_UN_MEMBER_STATUS,

SOURCE_DATA:car:side::VARCHAR AS COUNTRY_DRIVING_LANE,

CURRENT_TIMESTAMP(6) AS INSERT_DTS

FROM

{{ ref('country_details_raw') }} A,

LATERAL FLATTEN (A.SOURCE_DATA:continents) CON,

LATERAL FLATTEN (A.SOURCE_DATA:currencies) CUR

)

 

SELECT

COUNTRY_OFFICIAL_NAME,

COUNTRY_COMMON_NAME,

COUNTRY_LATLNG,

COUNTRY_CONTINENT_NAME,

COUNTRY_REGION_NAME,

COUNTRY_SUBREGION_NAME,

COUNTRY_CAPITAL_NAME,

COUNTRY_CAPITAL_LATLNG,

COUNTRY_TOTAL_AREA,

COUNTRY_POPULATION,

COUNTRY_CURRENCY,

COUNTRY_CURRENCY_NAME,

COUNTRY_CURRENCY_SYMBOL,

COUNTRY_FLAG,

COUNTRY_MAP,

COUNTRY_LANGUAGE,

COUNTRY_START_OF_WEEK,

COUNTRY_UN_MEMBER_STATUS,

COUNTRY_DRIVING_LANE,

INSERT_DTS

FROM country_details_transform